export default [
  {
    'id': 1,
    'car_brand': 'BMW',
    'car_model': '3 Series',
    'car_model_year': 2008,
    'car_color': 'Crimson',
    'car_price': '$9760.57',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 2,
    'car_brand': 'Infiniti',
    'car_model': 'G',
    'car_model_year': 1993,
    'car_color': 'Red',
    'car_price': '$8684.00',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 3,
    'car_brand': 'Mercedes-Benz',
    'car_model': 'SL-Class',
    'car_model_year': 1993,
    'car_color': 'Violet',
    'car_price': '$5757.74',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 4,
    'car_brand': 'Nissan',
    'car_model': 'Sentra',
    'car_model_year': 2007,
    'car_color': 'Turquoise',
    'car_price': '$2605.04',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 5,
    'car_brand': 'Chrysler',
    'car_model': 'Pacifica',
    'car_model_year': 2005,
    'car_color': 'Maroon',
    'car_price': '$3095.65',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 7
  },
  {
    'id': 6,
    'car_brand': 'Infiniti',
    'car_model': 'J',
    'car_model_year': 1993,
    'car_color': 'Pink',
    'car_price': '$1969.09',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 7,
    'car_brand': 'Buick',
    'car_model': 'Enclave',
    'car_model_year': 2010,
    'car_color': 'Violet',
    'car_price': '$9476.06',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 8,
    'car_brand': 'Oldsmobile',
    'car_model': 'Bravada',
    'car_model_year': 2000,
    'car_color': 'Yellow',
    'car_price': '$1003.10',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 9,
    'car_brand': 'Chevrolet',
    'car_model': 'Corvette',
    'car_model_year': 2009,
    'car_color': 'Purple',
    'car_price': '$5457.99',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 10,
    'car_brand': 'Mitsubishi',
    'car_model': 'Galant',
    'car_model_year': 2007,
    'car_color': 'Blue',
    'car_price': '$8101.01',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 11,
    'car_brand': 'BMW',
    'car_model': 'M3',
    'car_model_year': 1995,
    'car_color': 'Purple',
    'car_price': '$8534.32',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 12,
    'car_brand': 'Mitsubishi',
    'car_model': 'Raider',
    'car_model_year': 2007,
    'car_color': 'Indigo',
    'car_price': '$1942.01',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 13,
    'car_brand': 'Audi',
    'car_model': 'S4',
    'car_model_year': 2000,
    'car_color': 'Orange',
    'car_price': '$4691.78',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 14,
    'car_brand': 'Dodge',
    'car_model': 'Ram 3500',
    'car_model_year': 2004,
    'car_color': 'Orange',
    'car_price': '$9876.29',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 15,
    'car_brand': 'Corbin',
    'car_model': 'Sparrow',
    'car_model_year': 1999,
    'car_color': 'Indigo',
    'car_price': '$9250.70',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 16,
    'car_brand': 'Volvo',
    'car_model': 'V50',
    'car_model_year': 2011,
    'car_color': 'Fuscia',
    'car_price': '$8809.36',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 2
  },
  {
    'id': 17,
    'car_brand': 'Volkswagen',
    'car_model': 'Cabriolet',
    'car_model_year': 1999,
    'car_color': 'Puce',
    'car_price': '$7822.30',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 18,
    'car_brand': 'Mitsubishi',
    'car_model': 'Tundra',
    'car_model_year': 2009,
    'car_color': 'Teal',
    'car_price': '$1985.50',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 2
  },
  {
    'id': 19,
    'car_brand': 'Mercury',
    'car_model': 'Cougar',
    'car_model_year': 1986,
    'car_color': 'Red',
    'car_price': '$5716.01',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 20,
    'car_brand': 'Volkswagen',
    'car_model': 'Beetle',
    'car_model_year': 1965,
    'car_color': 'Green',
    'car_price': '$5795.17',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 21,
    'car_brand': 'Infiniti',
    'car_model': 'QX',
    'car_model_year': 1998,
    'car_color': 'Turquoise',
    'car_price': '$5112.08',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 22,
    'car_brand': 'Porsche',
    'car_model': 'Cayenne',
    'car_model_year': 2003,
    'car_color': 'Fuscia',
    'car_price': '$2508.20',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 23,
    'car_brand': 'Chevrolet',
    'car_model': 'Corvette',
    'car_model_year': 1987,
    'car_color': 'Teal',
    'car_price': '$1747.91',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 24,
    'car_brand': 'BMW',
    'car_model': 'M3',
    'car_model_year': 2010,
    'car_color': 'Red',
    'car_price': '$6452.52',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 7
  },
  {
    'id': 25,
    'car_brand': 'Hyundai',
    'car_model': 'Tucson',
    'car_model_year': 2006,
    'car_color': 'Crimson',
    'car_price': '$5532.12',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 26,
    'car_brand': 'Infiniti',
    'car_model': 'M',
    'car_model_year': 2011,
    'car_color': 'Khaki',
    'car_price': '$2790.28',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 27,
    'car_brand': 'Hummer',
    'car_model': 'H1',
    'car_model_year': 2000,
    'car_color': 'Indigo',
    'car_price': '$9947.72',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 28,
    'car_brand': 'Dodge',
    'car_model': 'Dynasty',
    'car_model_year': 1993,
    'car_color': 'Khaki',
    'car_price': '$5716.86',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 29,
    'car_brand': 'Ford',
    'car_model': 'Explorer',
    'car_model_year': 1996,
    'car_color': 'Indigo',
    'car_price': '$8215.53',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 30,
    'car_brand': 'Suzuki',
    'car_model': 'Equator',
    'car_model_year': 2010,
    'car_color': 'Blue',
    'car_price': '$3160.29',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 31,
    'car_brand': 'Mercury',
    'car_model': 'Monterey',
    'car_model_year': 2007,
    'car_color': 'Mauv',
    'car_price': '$4428.36',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 32,
    'car_brand': 'Bentley',
    'car_model': 'Continental Super',
    'car_model_year': 2011,
    'car_color': 'Yellow',
    'car_price': '$9505.03',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 33,
    'car_brand': 'Dodge',
    'car_model': 'Ramcharger',
    'car_model_year': 1992,
    'car_color': 'Fuscia',
    'car_price': '$5913.65',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 34,
    'car_brand': 'Mercedes-Benz',
    'car_model': 'SLK-Class',
    'car_model_year': 2008,
    'car_color': 'Orange',
    'car_price': '$6967.11',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 35,
    'car_brand': 'Hyundai',
    'car_model': 'Tiburon',
    'car_model_year': 2004,
    'car_color': 'Indigo',
    'car_price': '$3578.98',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 36,
    'car_brand': 'Mitsubishi',
    'car_model': 'Outlander',
    'car_model_year': 2005,
    'car_color': 'Orange',
    'car_price': '$8997.46',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 37,
    'car_brand': 'Honda',
    'car_model': 'Crosstour',
    'car_model_year': 2012,
    'car_color': 'Pink',
    'car_price': '$2039.27',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 38,
    'car_brand': 'Dodge',
    'car_model': 'Caravan',
    'car_model_year': 2004,
    'car_color': 'Teal',
    'car_price': '$3928.23',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 39,
    'car_brand': 'Dodge',
    'car_model': 'Caravan',
    'car_model_year': 1999,
    'car_color': 'Maroon',
    'car_price': '$3194.00',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 40,
    'car_brand': 'BMW',
    'car_model': 'Z4',
    'car_model_year': 2003,
    'car_color': 'Indigo',
    'car_price': '$8365.14',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 7
  },
  {
    'id': 41,
    'car_brand': 'Dodge',
    'car_model': 'Durango',
    'car_model_year': 1999,
    'car_color': 'Crimson',
    'car_price': '$5967.29',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 42,
    'car_brand': 'Lotus',
    'car_model': 'Esprit',
    'car_model_year': 2001,
    'car_color': 'Teal',
    'car_price': '$3032.28',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 43,
    'car_brand': 'Audi',
    'car_model': 'A5',
    'car_model_year': 2009,
    'car_color': 'Fuscia',
    'car_price': '$3607.53',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 44,
    'car_brand': 'Acura',
    'car_model': 'RL',
    'car_model_year': 2000,
    'car_color': 'Indigo',
    'car_price': '$1001.28',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 45,
    'car_brand': 'Maserati',
    'car_model': 'Quattroporte',
    'car_model_year': 2011,
    'car_color': 'Maroon',
    'car_price': '$8784.31',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 46,
    'car_brand': 'Mercury',
    'car_model': 'Sable',
    'car_model_year': 1987,
    'car_color': 'Red',
    'car_price': '$3436.89',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 47,
    'car_brand': 'Hyundai',
    'car_model': 'Tiburon',
    'car_model_year': 1999,
    'car_color': 'Indigo',
    'car_price': '$9448.86',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 5
  },
  {
    'id': 48,
    'car_brand': 'Dodge',
    'car_model': 'Durango',
    'car_model_year': 2001,
    'car_color': 'Green',
    'car_price': '$6010.96',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 49,
    'car_brand': 'Volkswagen',
    'car_model': 'New Beetle',
    'car_model_year': 2012,
    'car_color': 'Goldenrod',
    'car_price': '$2943.92',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 2
  },
  {
    'id': 50,
    'car_brand': 'Mitsubishi',
    'car_model': 'Lancer',
    'car_model_year': 2011,
    'car_color': 'Green',
    'car_price': '$4310.90',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 7
  },
  {
    'id': 51,
    'car_brand': 'Mercury',
    'car_model': 'Cougar',
    'car_model_year': 1997,
    'car_color': 'Goldenrod',
    'car_price': '$7416.15',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 52,
    'car_brand': 'Hummer',
    'car_model': 'H1',
    'car_model_year': 1995,
    'car_color': 'Violet',
    'car_price': '$2778.07',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 53,
    'car_brand': 'Toyota',
    'car_model': 'MR2',
    'car_model_year': 1985,
    'car_color': 'Green',
    'car_price': '$4391.16',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 2
  },
  {
    'id': 54,
    'car_brand': 'Dodge',
    'car_model': 'Charger',
    'car_model_year': 1969,
    'car_color': 'Fuscia',
    'car_price': '$6623.60',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 55,
    'car_brand': 'Mercury',
    'car_model': 'Cougar',
    'car_model_year': 1994,
    'car_color': 'Pink',
    'car_price': '$4861.19',
    'car_fuel': 'diesel',
    'car_doors': 5,
    'car_seats': 4
  },
  {
    'id': 56,
    'car_brand': 'Chevrolet',
    'car_model': 'Express 1500',
    'car_model_year': 1997,
    'car_color': 'Orange',
    'car_price': '$2211.31',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 7
  },
  {
    'id': 57,
    'car_brand': 'Lexus',
    'car_model': 'ES',
    'car_model_year': 1991,
    'car_color': 'Aquamarine',
    'car_price': '$7453.33',
    'car_fuel': 'petrol',
    'car_doors': 5,
    'car_seats': 7
  },
  {
    'id': 58,
    'car_brand': 'Pontiac',
    'car_model': 'Grand Prix',
    'car_model_year': 1993,
    'car_color': 'Violet',
    'car_price': '$1305.35',
    'car_fuel': 'diesel',
    'car_doors': 3,
    'car_seats': 4
  },
  {
    'id': 59,
    'car_brand': 'Toyota',
    'car_model': '4Runner',
    'car_model_year': 1993,
    'car_color': 'Purple',
    'car_price': '$2824.42',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 5
  },
  {
    'id': 60,
    'car_brand': 'Acura',
    'car_model': 'Integra',
    'car_model_year': 1994,
    'car_color': 'Goldenrod',
    'car_price': '$9410.50',
    'car_fuel': 'petrol',
    'car_doors': 3,
    'car_seats': 2
  }
]
